import Head from 'next/head'
import Background from './components/Background'

export default function Home() {
  return (
    <div>
      <Head>
        <title>A Next Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Background />    
      </main>       
    </div>
  )
}
